on:
  pull_request: {}
  push:
    branches:
      - 'main*'
    tags-ignore:
      - '**'
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
jobs:
  build:
    strategy:
      matrix:
        name: [ macos, windows ]
        include:
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
