on:
  pull_request: {}
  push:
    branches:
      - 'main*'
    tags-ignore:
      - '**'
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
