on:
  pull_request: {}
  push:
    branches:
      - 'main*'
    tags-ignore:
      - '**'
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
jobs:
  build:
    strategy:
      matrix:
        name: [ linux, macos ]
        include:
          # always use the oldest still supported LTS version of github actions
          - name: linux
            os: ubuntu-20.04
          - name: macos
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
